// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJU_pb3gVZDpXFFVXf9C-z5a-nmWUCAV8',
    appId: '1:543596770076:web:c4cfa757c29a420062c0d9',
    messagingSenderId: '543596770076',
    projectId: 'stu-driver-app-db',
    authDomain: 'stu-driver-app-db.firebaseapp.com',
    databaseURL: 'https://stu-driver-app-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stu-driver-app-db.appspot.com',
    measurementId: 'G-9FYJ2C98TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVpTbDGE4sNvDE5hfpZsnAkCXcO5wDphQ',
    appId: '1:543596770076:android:4dfd3f2450c65d8762c0d9',
    messagingSenderId: '543596770076',
    projectId: 'stu-driver-app-db',
    databaseURL: 'https://stu-driver-app-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stu-driver-app-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRHEpr2LnyZoT8Qo4pR9At2Pa9mFNvnnc',
    appId: '1:543596770076:ios:59936fe98889a54762c0d9',
    messagingSenderId: '543596770076',
    projectId: 'stu-driver-app-db',
    databaseURL: 'https://stu-driver-app-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stu-driver-app-db.appspot.com',
    iosBundleId: 'com.example.stuDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRHEpr2LnyZoT8Qo4pR9At2Pa9mFNvnnc',
    appId: '1:543596770076:ios:2bc896666a0b99fa62c0d9',
    messagingSenderId: '543596770076',
    projectId: 'stu-driver-app-db',
    databaseURL: 'https://stu-driver-app-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'stu-driver-app-db.appspot.com',
    iosBundleId: 'com.example.stuDriver.RunnerTests',
  );
}
